### ISSUE TITLE
Loading a script tag with attributes

### ISSUE THREAD

**Issue by jongold** [DerMambo/wait-on-lib#14]
Hey - nice work on this; I just can't figure out how to make it do what I want.

I'm trying to use Dropbox's [Chooser](https://www.dropbox.com/developers/dropins/chooser/js) script; can't figure out how to pass the extra params to the loader.

The script worked fine on its own in my <head> tag, but since I moved to using `Meteor.settings` to store my API key, I've had to take it out of the <head> so I could use the `Meteor.settings` object as a variable.

Any ideas?
```html
<script type="text/javascript" src="https://www.dropbox.com/static/api/2/dropins.js" id="dropboxjs" data-app-key=settings.dropboxClientId></script>
```

**Comment by mgrubinger** [comment]
Hey! I just had the same issue. You don't necessarily have to provide the API key via data-app-key, you can set it later using 
```
Dropbox.appKey = 'YOUR-KEY'
```
Just set this before you call Dropbox.choose(options); and you should be fine.

Passing parameters to the IRLibLoader would still be nice though ;)

**Comment by jongold** [comment]
Ahh nice. In the end I went for
```js
Meteor.startup(function(){
  $('head').append('<script type="text/javascript" src="https://www.dropbox.com/static/api/2/dropins.js" id="dropboxjs" data-app-key=' + Meteor.settings.public.dropboxClientId + '></script>');
});
```

- not sure what the tradeoffs are but I needed to ship this thing :)
